# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: javac -cp "src/" Projects/P1/src/*.java
        
  Pacman-is_ghost_in_range:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Projects/P1
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Pacman is_ghost_in_range test compilation
        run: javac -cp "tests/junit-4.10.jar:tests/*:src/*" src/*.java tests/TestGhostInRange.java
      - name:  run Pacman is_ghost_in_range test
        run: java -cp "tests/junit-4.10.jar:src/:tests/" -Djava.awt.headless=true org.junit.runner.JUnitCore TestGhostInRange

  Ghost-is_pacman_in_range:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Projects/P1
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Ghost is_pacman_in_range test compilation
        run: javac -cp "tests/junit-4.10.jar:tests/*:src/*" src/*.java tests/TestPacManInRange.java
      - name:  run Ghost is_ghost_in_range test
        run: java -cp "tests/junit-4.10.jar:src/:tests/" -Djava.awt.headless=true org.junit.runner.JUnitCore TestPacManInRange
