# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  Pac-Man-get_valid_moves:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Projects/P1
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile TestPacManValidMoves
        run: javac -cp "tests/junit-4.10.jar:tests/*:src/*" src/*.java tests/TestPacManValidMoves.java
      - name: Run TestPacManValidMoves
        run: java -cp "tests/junit-4.10.jar:src/:tests/" -Djava.awt.headless=true org.junit.runner.JUnitCore TestPacManValidMoves
  Ghost-get_valid_moves:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Projects/P1
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile TestGhostValidMoves
        run: javac -cp "tests/junit-4.10.jar:tests/*:src/*" src/*.java tests/TestGhostValidMoves.java
      - name: Run TestGhostValidMoves
        run: java -cp "tests/junit-4.10.jar:src/:tests/" -Djava.awt.headless=true org.junit.runner.JUnitCore TestGhostValidMoves
  MapMove:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Projects/P1
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile TestMapMove
        run: javac -cp "tests/junit-4.10.jar:tests/*:src/*" src/*.java tests/TestMapMove.java
      - name: Run TestMapMove
        run: java -cp "tests/junit-4.10.jar:src/:tests/" -Djava.awt.headless=true org.junit.runner.JUnitCore TestMapMove

